# Deleting DBs

rm database/database.sqlite

rm database/adipose-subcutaneous.sqlite
rm database/adipose-visceral-omentum.sqlite
rm database/adrenal-gland.sqlite
rm database/artery-aorta.sqlite
rm database/artery-coronary.sqlite
rm database/artery-tibial.sqlite
rm database/bladder.sqlite
rm database/brain-amygdala.sqlite
rm database/brain-anterior-cingulate-cortex-ba24.sqlite
rm database/brain-caudate-basal-ganglia.sqlite
rm database/brain-cerebellar-hemisphere.sqlite
rm database/brain-cerebellum.sqlite
rm database/brain-cortex.sqlite
rm database/brain-frontal-cortex-ba9.sqlite
rm database/brain-hippocampus.sqlite
rm database/brain-hypothalamus.sqlite
rm database/brain-nucleus-accumbens-basal-ganglia.sqlite
rm database/brain-putamen-basal-ganglia.sqlite
rm database/brain-spinal-cord-cervical-c-1.sqlite
rm database/brain-substantia-nigra.sqlite
rm database/breast-mammary-tissue.sqlite
rm database/cells-ebv-transformed-lymphocytes.sqlite
rm database/cells-transformed-fibroblasts.sqlite
rm database/colon-sigmoid.sqlite
rm database/colon-transverse.sqlite
rm database/esophagus-gastroesophageal-junction.sqlite
rm database/esophagus-mucosa.sqlite
rm database/esophagus-muscularis.sqlite
rm database/heart-atrial-appendage.sqlite
rm database/heart-left-ventricle.sqlite
rm database/kidney-cortex.sqlite
rm database/liver.sqlite
rm database/lung.sqlite
rm database/minor-salivary-gland.sqlite
rm database/muscle-skeletal.sqlite
rm database/nerve-tibial.sqlite
rm database/ovary.sqlite
rm database/pancreas.sqlite
rm database/pituitary.sqlite
rm database/prostate.sqlite
rm database/skin-not-sun-exposed-suprapubic.sqlite
rm database/skin-sun-exposed-lower-leg.sqlite
rm database/small-intestine-terminal-ileum.sqlite
rm database/spleen.sqlite
rm database/stomach.sqlite
rm database/testis.sqlite
rm database/thyroid.sqlite
rm database/uterus.sqlite
rm database/vagina.sqlite
rm database/whole-blood.sqlite


# Touching DBs

touch database/database.sqlite

touch database/adipose-subcutaneous.sqlite
touch database/adipose-visceral-omentum.sqlite
touch database/adrenal-gland.sqlite
touch database/artery-aorta.sqlite
touch database/artery-coronary.sqlite
touch database/artery-tibial.sqlite
touch database/bladder.sqlite
touch database/brain-amygdala.sqlite
touch database/brain-anterior-cingulate-cortex-ba24.sqlite
touch database/brain-caudate-basal-ganglia.sqlite
touch database/brain-cerebellar-hemisphere.sqlite
touch database/brain-cerebellum.sqlite
touch database/brain-cortex.sqlite
touch database/brain-frontal-cortex-ba9.sqlite
touch database/brain-hippocampus.sqlite
touch database/brain-hypothalamus.sqlite
touch database/brain-nucleus-accumbens-basal-ganglia.sqlite
touch database/brain-putamen-basal-ganglia.sqlite
touch database/brain-spinal-cord-cervical-c-1.sqlite
touch database/brain-substantia-nigra.sqlite
touch database/breast-mammary-tissue.sqlite
touch database/cells-ebv-transformed-lymphocytes.sqlite
touch database/cells-transformed-fibroblasts.sqlite
touch database/colon-sigmoid.sqlite
touch database/colon-transverse.sqlite
touch database/esophagus-gastroesophageal-junction.sqlite
touch database/esophagus-mucosa.sqlite
touch database/esophagus-muscularis.sqlite
touch database/heart-atrial-appendage.sqlite
touch database/heart-left-ventricle.sqlite
touch database/kidney-cortex.sqlite
touch database/liver.sqlite
touch database/lung.sqlite
touch database/minor-salivary-gland.sqlite
touch database/muscle-skeletal.sqlite
touch database/nerve-tibial.sqlite
touch database/ovary.sqlite
touch database/pancreas.sqlite
touch database/pituitary.sqlite
touch database/prostate.sqlite
touch database/skin-not-sun-exposed-suprapubic.sqlite
touch database/skin-sun-exposed-lower-leg.sqlite
touch database/small-intestine-terminal-ileum.sqlite
touch database/spleen.sqlite
touch database/stomach.sqlite
touch database/testis.sqlite
touch database/thyroid.sqlite
touch database/uterus.sqlite
touch database/vagina.sqlite
touch database/whole-blood.sqlite
